### ISSUE TITLE
Error: ENOENT: no such file or directory while trying to generate the code

### ISSUE THREAD

**Issue by DaniloMurer** [Valks-Minecraft-Plugins/Skeleton-Generator-JS#5]
The error occured when I tried to set the parameters over the website. The values from the config.js file do work.

error code:
The following values can be set manually via console: groupid, artifactid, description, discord

Generating skeleton..
Finished generating skeleton
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'C:\Users\JADA\Documents\Applikationen\Web\flexbox\whatevfer\dist\Danilo\src\main\java\danilo\jakob\danilo\Danilo.java'
Emitted 'error' event on WriteStream instance at:
    at internal/fs/streams.js:376:12
    at FSReqCallback.oncomplete (fs.js:155:23) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'Documents\\Applikationen\\Web\\flexbox\\whatevfer\\dist\\Danilo\\src\\main\\java\\danilo\\jakob\\danilo\\Danilo.java'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by valkyrienyanko** [comment]
Most likely related to #2 if you your groupId was not 3 parts.

**Comment by valkyrienyanko** [comment]
9a90ea6 solved this
